inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.3

Style/ConditionalAssignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - spec/**/*
