inherit_gem:
  rubocop-govuk:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.3

Style/ConditionalAssignment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - spec/**/*
