development:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] || "mongodb://localhost/govuk_content_development" %>
      options:
        write:
          w: 1

test:
  clients:
    default:
      uri: <%= ENV["TEST_MONGODB_URI"] || "mongodb://localhost/specialist_publisher_rebuild_test" %>
      options:
        write:
          w: 1

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
      options:
        write:
          w: <%= ENV["MONGO_WRITE_CONCERN"] || "majority" %>
