development:
  clients:
    default:
      uri: mongodb://localhost/specialist_publisher_rebuild_development
      options:
        write:
          w: 1

test:
  clients:
    default:
      uri: mongodb://localhost/specialist_publisher_rebuild_test
      options:
        write:
          w: 1

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        write:
          w: majority
